public with sharing class SendMail {
    
    public static void SendMail(Id contId) {

        System.debug('Id' + contId);
        // String cName = c.Name;
        // Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        // mail.setToAddresses(new String[] {'paulawambui@gmail.com'});
        // mail.setSubject('Thank you for your payment!');
        // String messageBody = '<html><body>Dear ' + cName + ',<br/> We have successfully processed your payment. <br/><br/> Thank you for your business! <br/><br/> Mom Relaunch</body>  </html>';
        // mail.setHtmlBody(messageBody); 
        // Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    }
}
